---
# tasks file for chap13kubepackage
- name: Install the latest version of docker
  ansible.builtin.yum:
    name: docker
    state: latest

- name: Install the latest version of docker
  ansible.builtin.yum:
    name: kubelet
    state: latest

- name: Start the services of Docker
  ansible.builtin.shell: |
    systemctl start docker
    systemctl enable docker
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubect1"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    cat <<EOF â˜ sudo tee /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-e17-\$basearch
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOF

